name: futbolcark
description: Futbol kariyer carki oyunu
publish_to: "none"
version: 0.0.18+18

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
